
# Builds a data volume container to host Chef        
# cookbooks that we want provisioned into our image. 
chefdata:
    container_name: chefdata
    build: base_embedded
    

# Attach an image that contains a Chef installation. 
chefclient:
    container_name: chefclient
    build: base_embedded/chefclient
    command: /bin/true


baseapp:
    container_name: baseapp 
    build: .
    volumes_from:
        - chefdata
        - chefclient
    environment:
        PATH: "/opt/chef/bin:$PATH"
    entrypoint: "/opt/chef/bin/chef-client"
    command: "-c /tmp/chef/zero.rb -z -j /tmp/chef/first-boot.json"